apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true
        description: URL of the code repository from which the feature flag will be removed. For example `https://github.com/my-organisation/my-project`     
      flag_name:
        type: string
        required: true
        description: Feature flag name.
      replacement_value:
        type: string
        required: true
        description: The value to replace the flag reference with, e.g. true/false (Boolean flags), 'string-value' (String flags), 123.456 (Number flags).
jobs:
  build:
    steps:
      - name: Print inputs                   
        uses: docker://alpine:3.18
        shell: sh                                                                                                                                                 
        run: |
          echo "flag_name: ${{ inputs.flag_name }}"                                                                                                               
          echo "replacement_value: ${{ inputs.replacement_value }}"
          echo "repository_url: ${{ inputs.repository_url }}"
